### ISSUE TITLE
Compatibility issues with 32-bit systems

### ISSUE THREAD

**Issue by thad4002** [Suprnova/Shell-City-Mod-Loader#1]
This doesn't work on 32-bit Windows 7.

**Comment by Suprnova** [comment]
Resolved in [v0.2](https://github.com/Suprnova/Shell-City-Mod-Loader/releases/tag/v0.2). Download the x86 version of the application, ensure you have .NET Core 3.1 installed, and you should be able to run it. If any issues arise as a result of the 32-bit version of Shell City, this issue should be reopened.
